//! Owned attachment IO: staging, validation, resumable upload publication and
//! materialization into verified native blocks.

use anyhow::{Context, Result, bail, ensure};
use serde_json::{Value, json};
use std::path::Path;
use tokio_util::sync::CancellationToken;
use tokio::fs;
use tokio::io::{AsyncReadExt, AsyncSeekExt, AsyncWriteExt};

use crate::{manager::{AgentManager, safe_file_name}, state::StateStore};
use tau_net::blocks::*;
use crate::transcript::{AttachmentKind, AttachmentRequest, attachment_request, FILE_LIMIT, IMAGE_LIMIT};

pub struct ResolvedAttachment {
    pub file: fs::File,
    pub sha256: Option<String>,
    pub mime_type: &'static str,
    #[cfg(test)]
    pub size: u64,
}

impl AgentManager {
    pub async fn resolve_attachment(
        &self,
        id: &str,
        entry_id: &str,
    ) -> Result<ResolvedAttachment> {
        let entry = self.inner.state.entry(id,entry_id).await?;
        let request = attachment_request(&entry).context("Entry has no Tau attachment")?;
        open_attachment(&self.inner.config.attachment_root, &request).await
    }
}

pub(crate) fn image_mime(bytes: &[u8]) -> Option<&'static str> {
    if bytes.starts_with(b"\x89PNG\r\n\x1a\n") { Some("image/png") }
    else if bytes.starts_with(&[0xff,0xd8,0xff]) { Some("image/jpeg") }
    else if bytes.len() >= 12 && &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WEBP" { Some("image/webp") }
    else if bytes.starts_with(b"GIF87a") || bytes.starts_with(b"GIF89a") { Some("image/gif") }
    else if bytes.starts_with(b"BM") { Some("image/bmp") } else { None }
}
pub(crate) async fn regular_file(path: &Path) -> Result<fs::File> {
    let mut options = fs::OpenOptions::new(); options.read(true);
    #[cfg(unix)] options.custom_flags(libc::O_NONBLOCK);
    let file = options.open(path).await?;
    if !file.metadata().await?.is_file() { bail!("Path is not a regular file"); }
    Ok(file)
}
async fn open_attachment(root: &Path, request: &AttachmentRequest) -> Result<ResolvedAttachment> {
    let root = fs::canonicalize(root).await.context("Tau attachment root is unavailable")?;
    let path = fs::canonicalize(&request.path).await.context("Attachment is unavailable")?;
    if !path.starts_with(&root) || path == root { bail!("Attachment is outside the Tau outbox"); }
    let mut file = regular_file(&path).await?;
    let size = file.metadata().await?.len();
    let limit = match request.kind { AttachmentKind::Image => IMAGE_LIMIT, AttachmentKind::File => FILE_LIMIT };
    if size > limit { bail!("Attachment exceeds the {limit} byte limit"); }
    let mime_type = if request.kind == AttachmentKind::Image {
        let mut header = [0; 12]; let length = file.read(&mut header).await?;
        file.seek(std::io::SeekFrom::Start(0)).await?;
        match image_mime(&header[..length]) {
            Some(mime @ ("image/png" | "image/jpeg" | "image/webp")) => mime,
            _ => bail!("Attachment is not a supported image"),
        }
    } else { "application/octet-stream" };
    Ok(ResolvedAttachment { file, sha256:request.sha256.clone(), mime_type, #[cfg(test)] size })
}

async fn attachment_result(path: &Path, file: &mut fs::File, caption: Option<&str>) -> Result<Value> {
    let size = file.metadata().await?.len();
    if size > FILE_LIMIT { bail!("Attachment exceeds the {FILE_LIMIT} byte limit"); }
    file.seek(std::io::SeekFrom::Start(0)).await?;
    let mut header = [0; 12]; let length = file.read(&mut header).await?;
    let image = size <= IMAGE_LIMIT && matches!(image_mime(&header[..length]), Some("image/png" | "image/jpeg" | "image/webp"));
    use sha2::Digest;
    file.seek(std::io::SeekFrom::Start(0)).await?;
    let mut hash=sha2::Sha256::new();let mut total=0u64;let mut buffer=[0;16384];
    loop {let n=file.read(&mut buffer).await?;if n==0 {break;}total+=n as u64;if total>FILE_LIMIT {bail!("Attachment changed while sealing");}hash.update(&buffer[..n]);}
    if total!=size {bail!("Attachment changed while sealing");}
    let sha256=format!("{:x}",hash.finalize());
    Ok(json!({"content":[{"type":"text","text":format!("{} queued for Tau: {}", if image {"Image"} else {"File"}, path.file_name().unwrap().to_string_lossy())}],
        "details":{"tauAttachment":{"version":1,"kind":if image {"image"} else {"file"},"path":path,"caption":caption,"size":size,"sha256":sha256}}}))
}

// Both local files and provider-generated bytes take this path. A partial/cancelled
// copy is removed; a published attachment has its own private, durable file.
async fn stage_attachment(root: &Path, name: &std::ffi::OsStr, source: impl tokio::io::AsyncRead + Unpin, caption: Option<&str>, cancel: &CancellationToken) -> Result<Value> {
    // Retained output is user data, including ambiguous paid-image results.
    // Bound new publication, but never garbage-collect unclaimed paid outputs.
    static GATE:tokio::sync::Mutex<()>=tokio::sync::Mutex::const_new(());
    let _gate=GATE.lock().await;
    let owned=root.to_owned();
    tokio::task::spawn_blocking(move ||->Result<()> {
        let mut pending=vec![owned];let mut bytes=0u64;let mut entries=0;
        while let Some(path)=pending.pop() {
            for entry in std::fs::read_dir(path)? {
                let entry=entry?;entries+=1;if entries>100000 {bail!("Outbox entry quota reached; archive retained outputs first");}
                let kind=entry.file_type()?;
                if kind.is_dir() {pending.push(entry.path());}
                else if kind.is_file() {bytes=bytes.saturating_add(entry.metadata()?.len());}
                if bytes+FILE_LIMIT>4*1024*1024*1024 {bail!("Retained outbox quota reached; archive outputs before staging another file");}
            }
        }Ok(())
    }).await??;
    let directory = tempfile::Builder::new().prefix(".tau-").tempdir_in(root)?;
    let path = directory.path().join(name);
    let mut options = fs::OpenOptions::new(); options.create_new(true).read(true).write(true);
    #[cfg(unix)] options.mode(0o600);
    let mut file = options.open(&path).await?;
    let mut source = source.take(FILE_LIMIT + 1);
    tokio::select! {
        _ = cancel.cancelled() => bail!("Attachment staging cancelled"),
        result = tokio::io::copy(&mut source, &mut file) => { result?; }
    }
    file.flush().await?;
    let result = attachment_result(&path, &mut file, caption).await?;
    file.sync_all().await?;
    #[cfg(unix)] {
        fs::File::open(directory.path()).await?.sync_all().await?;
        fs::File::open(root).await?.sync_all().await?;
    }
    if cancel.is_cancelled() { bail!("Attachment staging cancelled"); }
    let _ = directory.keep();
    Ok(result)
}

pub(crate) async fn send_file(root: &Path, source: &Path, caption: Option<&str>, cancel: &CancellationToken) -> Result<Value> {
    let caption = caption.map(str::trim).filter(|value| !value.is_empty());
    if caption.is_some_and(|value| value.chars().count() > 1024) { bail!("Caption exceeds 1024 characters"); }
    if cancel.is_cancelled() { bail!("Attachment staging cancelled"); }
    let source = fs::canonicalize(source).await.context("Attachment does not exist")?;
    let file = regular_file(&source).await?;
    if file.metadata().await?.len() > FILE_LIMIT { bail!("Attachment exceeds the {FILE_LIMIT} byte limit"); }
    let root = fs::canonicalize(root).await.context("Tau attachment root is unavailable")?;
    // A delivered file is an owned snapshot, even if its original is already
    // under outbox. Later edits to that original must not change an old card.
    stage_attachment(&root, source.file_name().context("Attachment has no file name")?, file, caption, cancel).await
}

pub(crate) async fn generated_image(root: &Path, bytes: &[u8], cancel: &CancellationToken) -> Result<Value> {
    let result:Result<Value>=async {
        let root = fs::canonicalize(root).await.context("Tau attachment root is unavailable")?;
        let name = format!("generated-{}.png", uuid::Uuid::new_v4());
        stage_attachment(&root, std::ffi::OsStr::new(&name), bytes, None, cancel).await
    }.await;
    result.map_err(|error|anyhow::anyhow!("OpenAI generated the image, but Tau could not stage it. Do not retry automatically; ask the user before another generation request. {error:#}"))
}

// store:false cannot replay a generated-image item by ID. Rehydrate the staged
// image only when constructing provider context, never into history or the wire.
pub(crate) async fn image_reference(root: &Path, request: &AttachmentRequest) -> Result<Value> {
    use base64::{Engine as _, engine::general_purpose::STANDARD};
    let resolved = open_attachment(root, request).await?;
    let mut bytes = Vec::new(); resolved.file.take(IMAGE_LIMIT + 1).read_to_end(&mut bytes).await?;
    if bytes.len() as u64 > IMAGE_LIMIT { bail!("Reference image exceeds 10 MB"); }
    if let Some(expected)=resolved.sha256 {use sha2::Digest;if format!("{:x}",sha2::Sha256::digest(&bytes))!=expected {bail!("Saved image failed integrity verification; do not regenerate automatically");}}
    Ok(json!({"type":"image_url","image_url":{"url":format!("data:{};base64,{}", resolved.mime_type, STANDARD.encode(bytes))}}))
}

#[cfg(test)]
#[path = "../tests/unit/attachments.rs"]
mod snapshot_tests;

struct StagedFile { state:StateStore, id:String }
impl Drop for StagedFile {
    fn drop(&mut self) {
        // Cancellation may happen while the QUIC stream is being dropped. Any
        // interrupted cleanup is also performed transactionally at startup.
        let state=self.state.clone(); let id=self.id.clone();
        tokio::spawn(async move { let _=state.access(move |db| {let tx=db.transaction()?; tau_block_store::discard_stage(&tx,&id)?;tx.commit()?;Ok(())}).await; });
    }
}
impl AgentManager {
    pub(crate) async fn materialize_file(&self, scope: &str, id: &str) -> Result<()> {
        let scope=scope.to_owned(); let id=id.to_owned();
        let read_header = || {let scope=scope.clone(); let id=id.clone(); self.inner.state.read(move |db|tau_block_store::header(db,&scope,&id))};
        let Some(h)=read_header().await? else {return Ok(());};
        if h.meta.get("materialized") != Some(&json!(false)) {return Ok(());}
        let _permit=self.inner.block_imports.acquire().await?;
        let Some(h)=read_header().await? else {return Ok(());};
        if h.meta.get("materialized") != Some(&json!(false)) {return Ok(());}
        let entry=h.meta["entry"].as_str().context("File has no source reference")?;
        let attachment=self.resolve_attachment(&scope,entry).await?;
        let mut file=attachment.file;
        let before=file.metadata().await?;
        ensure!(before.len() <= tau_net::blocks::MAX_BLOCK_BYTES,"File is too large");
        let staging=StagedFile {state:self.inner.state.clone(),id:uuid::Uuid::new_v4().to_string()};
        let mut offset=0; let mut buffer=vec![0; tau_net::blocks::BLOCK_CHUNK_BYTES*8];
        use sha2::Digest;
        use tokio::io::AsyncReadExt;
        let mut hash=sha2::Sha256::new();
        loop {
            let n=file.read(&mut buffer).await?;
            let bytes=buffer[..n].to_vec(); let stage=staging.id.clone();
            self.inner.state.access(move |db| {let tx=db.transaction()?;tau_block_store::stage_append(&tx,&stage,offset,&bytes)?;tx.commit()?;Ok(())}).await?;
            hash.update(&buffer[..n]); offset+=n as u64;
            if n==0 {break;}
        }
        let after=file.metadata().await?;
        ensure!(offset==before.len() && before.len()==after.len() && before.modified()?==after.modified()?,"File changed while importing");
        let digest=format!("{:x}",hash.finalize());
        ensure!(attachment.sha256.is_none_or(|expected|expected==digest),"Owned file failed integrity verification");
        let mut meta=h.meta.clone(); meta["materialized"]=json!(true);meta["sha256"]=json!(digest);
        let stage=staging.id.clone();
        self.inner.state.access(move |db| {
            let tx=db.transaction()?;
            let current=tau_block_store::header(&tx,&scope,&id)?.context("File no longer exists")?;
            if current.meta.get("materialized") == Some(&json!(false)) {tau_block_store::publish_stage(&tx,&stage,&scope,&id,meta)?;}
            else {tau_block_store::discard_stage(&tx,&stage)?;}
            tx.commit()?;Ok(())
        }).await
    }
}


impl AgentManager {
    pub(crate) async fn begin_upload(&self, spec: UploadSpec) -> Result<UploadStatus> {
        let expected=spec.clone();
        let status=self.inner.state.access(move |db| {
            if let UploadPurpose::File {session_id,..} = &spec.purpose {
                ensure!(db.query_row("SELECT EXISTS(SELECT 1 FROM sessions WHERE id=?1)",[session_id],|r|r.get::<_,bool>(0))?,"Chat no longer exists");
            }
            let tx = db.transaction()?;
            let result = tau_block_store::begin_upload(&tx,&spec)?;
            tx.commit()?;
            Ok(result)
        }).await?;
        if status.sealed && matches!(expected.purpose,UploadPurpose::File {..}) {
            let _permit=self.inner.block_imports.acquire().await?;
            let published=status.file.as_ref().context("Sealed upload has no owned file")?;
            let mut file=crate::attachments::regular_file(std::path::Path::new(&published.path)).await?;
            let mut hash=blake3::Hasher::new();let mut length=0u64;let mut buffer=[0;BLOCK_CHUNK_BYTES];
            loop {
                use tokio::io::AsyncReadExt;
                let n=file.read(&mut buffer).await?;if n==0 {break;}
                length+=n as u64;ensure!(length<=expected.length,"Published upload changed");hash.update(&buffer[..n]);
            }
            ensure!(length==expected.length && hash.finalize().to_hex().as_str()==expected.hash,"Published upload failed integrity verification; preserve the local original");
        }
        Ok(status)
    }
    pub(crate) async fn write_upload(&self, spec: UploadSpec, offset: u64, bytes: Vec<u8>) -> Result<()> {
        self.inner.state.access(move |db| {
            let tx = db.transaction()?;
            tau_block_store::write_upload(&tx,&spec,offset,&bytes)?;
            tx.commit()?;
            Ok(())
        }).await
    }
    pub(crate) async fn finish_upload(&self, spec: UploadSpec) -> Result<UploadStatus> {
        let gate={let mut gates=self.inner.upload_finishes.lock().await;gates.retain(|_,gate|gate.strong_count()>0);
            if let Some(gate)=gates.get(&spec.id).and_then(std::sync::Weak::upgrade) {gate} else {let gate=std::sync::Arc::new(tokio::sync::Mutex::new(()));gates.insert(spec.id.clone(),std::sync::Arc::downgrade(&gate));gate}};
        let finish=gate.lock_owned().await;
        let current = self.begin_upload(spec.clone()).await?;
        if current.sealed { return Ok(current); }
        let permit = self.inner.block_imports.clone().acquire_owned().await?;
        ensure!(current.offset == spec.length,"Upload is incomplete");
        let mut export = None;
        if let UploadPurpose::File {session_id,file_name} = &spec.purpose {
            tokio::fs::create_dir_all(&self.inner.config.upload_root).await?;
            let root = tokio::fs::canonicalize(&self.inner.config.upload_root).await?;
            let directory = root.join(session_id);
            tokio::fs::create_dir_all(&directory).await?;
            let directory = tokio::fs::canonicalize(directory).await?;
            ensure!(directory.starts_with(&root) && directory != root,"Unsafe upload directory");
            // The ID fixes the destination, so a lost final acknowledgement or
            // crash after rename never creates another attachment/path.
            let name = safe_file_name(file_name);
            let export_id=blake3::hash(&serde_json::to_vec(&spec)?).to_hex().to_string();
            let target = directory.join(format!("{export_id}-{name}"));
            let (id,session,path,size)=(spec.id.clone(),session_id.clone(),target.to_string_lossy().into_owned(),spec.length);
            self.inner.state.access(move |db| {
                let tx=db.transaction()?;
                use rusqlite::OptionalExtension;
                let existing:Option<(String,String,u64)>=tx.query_row("SELECT session,path,size FROM file_publications WHERE id=?1",[&id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).optional()?;
                if let Some(old)=existing {
                    ensure!(old==(session.clone(),path.clone(),size),"Retained publication ID is bound to a different file");
                } else {
                    let (count,bytes):(u64,u64)=tx.query_row("SELECT count(*),coalesce(sum(size),0) FROM file_publications",[],|r|Ok((r.get(0)?,r.get(1)?)))?;
                    ensure!(count<8192 && bytes+size<=4*1024*1024*1024,"Retained uploads quota reached; archive/delete chats before another upload");
                    tx.execute("INSERT INTO file_publications(id,session,path,size,created) VALUES(?1,?2,?3,?4,?5)",rusqlite::params![id,session,path,size,crate::agent::now_ms()/1000])?;
                }
                tx.execute("INSERT OR IGNORE INTO file_owners VALUES(?1,?2)",rusqlite::params![id,session])?;
                tx.commit()?;Ok(())
            }).await?;
            let temp = tempfile::NamedTempFile::new_in(&directory)?;
            let file = tokio::fs::File::from_std(temp.reopen()?);
            export = Some((temp,file,target,name,root));
        }
        let mut hash = blake3::Hasher::new();
        let mut offset = 0;
        while offset < spec.length {
            let id = spec.id.clone();
            let range = self.inner.state.read(move |db|tau_block_store::read(db,&BlockRequest {scope:UPLOAD_SCOPE.into(),id,version:1,offset,follow:false})).await?;
            ensure!(range.offset == offset && !range.bytes.is_empty(),"Upload has a missing range");
            hash.update(&range.bytes);
            if let Some((_,file,..)) = &mut export {file.write_all(&range.bytes).await?;}
            offset += range.bytes.len() as u64;
        }
        let hash = hash.finalize().to_hex().to_string();
        ensure!(offset == spec.length && hash == spec.hash,"Upload integrity check failed");
        // Publication is owned after complete verification. Cancelling the QUIC
        // stream cannot release its exclusion gates while rename/fsync is still
        // running on a blocking thread, nor orphan an untracked exported file.
        let manager=self.clone();let state=self.inner.state.clone();
        tokio::spawn(async move {
        let _permit=permit;let _finish=finish;let _publication=manager.inner.upload_publication.lock().await;
        if export.is_some() {
            let root=manager.inner.config.upload_root.clone();
            tokio::task::spawn_blocking(move ||->Result<()> {
                let mut pending=vec![root];let mut count=0u64;let mut size=0u64;
                while let Some(directory)=pending.pop() {for entry in std::fs::read_dir(directory)? {
                    let entry=entry?;count+=1;ensure!(count<=100000,"Retained upload entry quota reached");
                    let kind=entry.file_type()?;if kind.is_dir() {pending.push(entry.path());} else if kind.is_file() {size=size.saturating_add(entry.metadata()?.len());}
                    ensure!(size<=4*1024*1024*1024,"Retained upload byte quota reached; archive owned files before retrying");
                }}Ok(())
            }).await??;
        }
        let file = if let Some((temp,mut file,target,name,root)) = export {
            file.flush().await?; file.sync_all().await?; drop(file);
            let path = target.clone();
            tokio::task::spawn_blocking(move || -> Result<()> {
                temp.persist(&path)?;
                std::fs::File::open(path.parent().unwrap())?.sync_all()?;
                std::fs::File::open(&root)?.sync_all()?;
                if let Some(parent)=root.parent() {std::fs::File::open(parent)?.sync_all()?;}
                Ok(())
            }).await??;
            Some(tau_net::UploadedFile {name,path:target.to_str().context("Upload path is not UTF-8")?.into(),size:spec.length})
        } else {None};
        state.access(move |db| {
            let tx = db.transaction()?;
            if let UploadPurpose::File {session_id,..} = &spec.purpose {
                ensure!(tx.query_row("SELECT EXISTS(SELECT 1 FROM sessions WHERE id=?1)",[session_id],|r|r.get::<_,bool>(0))?,"Chat was deleted during upload");
            }
            if file.is_some() {tx.execute("UPDATE file_publications SET sealed=1 WHERE id=?1",[&spec.id])?;}
            let status = tau_block_store::seal_upload(&tx,&spec,&hash,file)?;
            tx.commit()?; Ok(status)
        }).await
        }).await?
    }
}

impl AgentManager {
    pub(crate) async fn maintain_uploads(&self)->Result<()> {
        // Exclude complete native publication, including detached final fsyncs.
        let _permit=self.inner.block_imports.acquire_many(2).await?;
        let expired=crate::agent::now_ms()/1000-7*24*3600;
        let candidates=self.inner.state.access(move |db| {
            Ok(db.prepare("SELECT id,path FROM file_publications p WHERE NOT EXISTS(SELECT 1 FROM file_owners o WHERE o.id=p.id) OR (sealed=0 AND created<?1) LIMIT 128")?
                .query_map([expired],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?)))?.collect::<rusqlite::Result<Vec<_>>>()?)
        }).await?;
        for (id,path) in candidates {
            let path=std::path::PathBuf::from(path);let root=&self.inner.config.upload_root;
            ensure!(path.starts_with(root) && path.strip_prefix(root)?.components().count()==2,"Quarantined upload outside the configured root; inspect storage manually");
            match tokio::fs::remove_file(&path).await {Ok(())=>{},Err(e) if e.kind()==std::io::ErrorKind::NotFound=>{},Err(e)=>return Err(e.into())}
            if let Some(parent)=path.parent() {let _=tokio::fs::remove_dir(parent).await;}
            self.inner.state.access(move |db| {
                let tx=db.transaction()?;tx.execute("DELETE FROM file_publications WHERE id=?1",[&id])?;
                tx.execute("DELETE FROM blocks WHERE scope='@uploads' AND id=?1",[&id])?;tx.commit()?;Ok(())
            }).await?;
        }
        self.inner.state.access(move |db| {
            let tx=db.transaction()?;
            tx.execute("DELETE FROM blocks WHERE scope='@uploads' AND position<?1",[expired])?;
            tx.execute("DELETE FROM blocks WHERE scope='@control' AND position<?1",[crate::agent::now_ms()/1000-24*3600])?;
            tx.execute("DELETE FROM block_changes WHERE scope='@control' AND id NOT IN (SELECT id FROM blocks WHERE scope='@control')",[])?;
            tx.commit()?;Ok(())
        }).await
    }
}
