[workspace]
members = ["crates/daemon", "crates/net", "crates/block-store", "crates/markdown", "crates/frontend", "crates/code-viewer"]
exclude = ["crates/windows"]
resolver = "2"

[workspace.dependencies]
sanscale = { git = "https://github.com/xpjb/sanscale", rev = "4325844c649dde6e2f1812a489ebca8d9b2ddadd" }
