[package]
name = "tau-setup"
version = "0.3.2"
edition = "2024"
build = "build.rs"

[build-dependencies]
winresource = "0.1"

[dependencies]
lzma-rs = "0.3"
semver = "1"
sha2 = "0.10"
tar = "0.4"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Storage_FileSystem",
    "Win32_UI_WindowsAndMessaging",
] }
