[package]
name = "tau-markdown"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
sanscale = { workspace = true }
ropey = { version = "1", default-features = false, features = ["simd"] }
unicode-segmentation = "1"

[features]
perf-counters = ["sanscale/perf-counters"]
