[package]
name = "tau-markdown"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
sanscale = { git = "https://github.com/xpjb/sanscale", rev = "2be4f316c3870d8cd9ba6e12b5e10b2af385bf2c" }
ropey = { version = "1", default-features = false, features = ["simd"] }
unicode-segmentation = "1"

[features]
perf-counters = ["sanscale/perf-counters"]
