[package]
name = "tau-launcher"
version = "0.4.3"
edition = "2024"
build = "build.rs"

[build-dependencies]
winresource = "0.1"

[target.'cfg(windows)'.dependencies]
sha2 = "0.10"
zip = { version = "8.6", default-features = false, features = ["deflate-flate2-zlib-rs"] }
windows-sys = { version = "0.61", features = [
    "Win32_System_Com_Urlmon",
    "Win32_UI_WindowsAndMessaging",
] }
